name: K-Updater

on:
  schedule:
    - cron: '0 0 * * *' # Запуск раз в сутки в 00:00 UTC
  workflow_dispatch: # Оставляем возможность ручного запуска

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install requests

      - name: Run Monitor
        run: python public_main.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add public_scr.txt last_id.txt
          # Коммитим изменения, если они есть
          git commit -m "Daily update: Added new keys from Telegram" || exit 0
          git push origin main
